service: nest-serverless-lambda-demo

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs14.x
 lambdaHashingVersion: 20201221
 region: ap-northeast-2
 stage: live

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}