service: study-board-server

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs14.x
 lambdaHashingVersion: 20201221
 region: ap-northeast-2
 stage: live
 iam:
  role:
      statements:
        - Effect: 'Allow'
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
          Resource:
            - 'arn:aws:dynamodb:ap-northeast-2:957582603404:table/StudyBoard_v3'
            - 'arn:aws:dynamodb:ap-northeast-2:957582603404:table/StudyBoard_v3/index/createdAt-index'

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}